[test_config]
force-clean = false
skip-clean = true
line-coverage = true
branch-coverage = false
test-timeout = "30s"
offline = true
target-dir = "./target/coverage"
exclude-files = ["target/*", "app/src/adapters/*", "prono_db/*"]
exclude = ["prono-db"]
